apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - cilium.yaml
  - infisical-namespace.yaml
  - infisical-repository.yaml
  - infisical-release.yaml
  - external-dns-namespace.yaml
  - external-dns-repository.yaml
  - external-dns-release_secrets.yaml
  - external-dns-release.yaml
