---

name: personal-wordpress

networks:
  frontend:
    external: true
  backend:
    external: true

services:
  db:
    image: mysql:8.0
    container_name: personal-wordpress-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - backend

  wordpress:
    depends_on:
      - db
    image: wordpress
    container_name: personal-wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./data:/var/www/html
    labels:
      traefik.enable: true
      traefik.external: true
      traefik.http.services.personalwordpress-prod-1.loadBalancer.server.port: 80
      traefik.http.routers.personalwordpress-prod-1-http.entrypoints: web
      traefik.http.routers.personalwordpress-prod-1-http.rule: Host(`wordpress.jakerob.pro`)
      traefik.http.routers.personalwordpress-prod-1-http.middlewares: websecure-redirect-permanent@file
      traefik.http.routers.personalwordpress-prod-1-https.entrypoints: websecure
      traefik.http.routers.personalwordpress-prod-1-https.rule: Host(`wordpress.jakerob.pro`)
      traefik.http.routers.personalwordpress-prod-1-https.tls: true
      traefik.http.routers.personalwordpress-prod-1-https.tls.certresolver: production
    networks:
      - backend
      - frontend
