---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-crds
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: ExternalArtifact
    name: infrastructure
  path: ./crds
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-crds
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: ExternalArtifact
    name: infrastructure
  path: ./controllers
  prune: true
  wait: true
  patches:
    - patch: |
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: cilium
          namespace: kube-system
        spec:
          values:
            k8sServiceHost: localhost
            k8sServicePort: 7445
            ipam:
              mode: kubernetes
            securityContext:
              capabilities:
                ciliumAgent:
                  - CHOWN
                  - KILL
                  - NET_ADMIN
                  - NET_RAW
                  - IPC_LOCK
                  - SYS_ADMIN
                  - SYS_RESOURCE
                  - DAC_OVERRIDE
                  - FOWNER
                  - SETGID
                  - SETUID
                cleanCiliumState:
                  - NET_ADMIN
                  - SYS_ADMIN
                  - SYS_RESOURCE
            cgroup:
              autoMount:
                enabled: false
              hostRoot: /sys/fs/cgroup
      target:
        kind: HelmRelease
        name: cilium
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: ExternalArtifact
    name: infrastructure
  path: ./configs
  prune: true
  # TODO:
  # patches:
  #   - patch: |
  #       - op: replace
  #         path: /spec/acme/server
  #         value: https://acme-v02.api.letsencrypt.org/directory
  #     target:
  #       kind: ClusterIssuer
  #       name: letsencrypt

# ---
# apiVersion: "cilium.io/v2alpha1"
# kind: CiliumLoadBalancerIPPool
# metadata:
#   name: proxmox-pool
# spec:
#   cidrs:
#   - cidr: "192.168.1.200/29"
# ---
# apiVersion: "cilium.io/v2alpha1"
# kind: CiliumL2AnnouncementPolicy
# metadata:
#   name: proxmox-l2-policy
# spec:
#   loadBalancerIPs: true