---

networks:
  dokploy-network:
    driver: overlay
    attachable: true
    name: dokploy-network
    external: true

volumes:
  dokploy-postgres:
    name: dokploy_postgres
  dokploy-redis:
    name: dokploy_redis
  dokploy-docker:
    name: dokploy_docker

secrets:
  dokploy_postgres_password:
    file: dokploy_postgres_password.txt

services:
  dokploy-postgres:
    image: postgres:16
    secrets:
      - dokploy_postgres_password
    environment:
      POSTGRES_USER: dokploy
      POSTGRES_DB: dokploy
      POSTGRES_PASSWORD_FILE: /run/secrets/dokploy_postgres_password
    networks:
      - dokploy-network
    volumes:
      - dokploy-postgres:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.role==manager

  dokploy-redis:
    image: redis:7
    networks:
      - dokploy-network
    volumes:
      - dokploy-redis:/data
    deploy:
      placement:
        constraints:
          - node.role==manager

  dokploy:
    image: docker.io/dokploy/dokploy:v0.26.6
    depends_on:
      - dokploy-postgres
      - dokploy-redis
    secrets:
      - dokploy_postgres_password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/dokploy_postgres_password
      # - ADVERTISE_ADDR=${ADVERTISE_ADDR:-localhost}
      # - RELEASE_TAG=${RELEASE_TAG:-latest}
    networks:
      - dokploy-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dokploy-data/applications:/etc/dokploy/applications
      - ./dokploy-data/logs:/etc/dokploy/logs
      - ./dokploy-data/monitoring:/etc/dokploy/monitoring
      - ./dokploy-data/schedules:/etc/dokploy/schedules
      - ./dokploy-data/ssh:/etc/dokploy/ssh
      - ./dokploy-data/volume-backups:/etc/dokploy/volume-backups
      - ../../../docker-compose/traefik/iad1-node-1/config-external/conf/dokploy/:/etc/dokploy/traefik
      - dokploy-docker:/root/.docker
    deploy:
      placement:
        constraints:
          - node.role==manager
    labels:
      traefik.enable: "true"
      traefik.docker.network: dokploy-network
      traefik.http.routers.dokploy-prod-1-http.entrypoints: web
      traefik.http.routers.dokploy-prod-1-http.rule: Host(`dokploy.iad1vpn.jakerob.pro`)
      traefik.http.routers.dokploy-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.dokploy-prod-1-https.entrypoints: websecure
      traefik.http.routers.dokploy-prod-1-https.rule: Host(`dokploy.iad1vpn.jakerob.pro`)
      traefik.http.routers.dokploy-prod-1-https.tls: "true"
      traefik.http.routers.dokploy-prod-1-https.tls.certresolver: cloudflare
