---
name: portainer

networks:
  backend:
    external: true
  frontend:
    external: true

services:
  portainer:
    image: portainer/portainer-ce:2.19.4-alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    networks:
      - frontend
      - backend
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.services.portainer-prod-1.loadbalancer.server.port: "9000"
      traefik.http.services.portainer-prod-1.loadbalancer.server.scheme: "http"
      traefik.http.routers.portainer-prod-1-http.entrypoints: "web"
      traefik.http.routers.portainer-prod-1-http.rule: "Host(`portainer.slc1.jakerob.pro`)"
      traefik.http.routers.portainer-prod-1-http.middlewares: websecure-redirect-permanent@file
      traefik.http.routers.portainer-prod-1-https.entrypoints: "websecure"
      traefik.http.routers.portainer-prod-1-https.rule: "Host(`portainer.slc1.jakerob.pro`)"
      traefik.http.routers.portainer-prod-1-https.tls: "true"
      traefik.http.routers.portainer-prod-1-https.tls.certresolver: "cloudflare"
