http:
  routers:
    pihole-prod-1-http:
      entrypoints: web
      rule: "Host(`pihole.lhr1.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: pihole-prod-1
    pihole-prod-1-https:
      entrypoints: websecure
      rule: "Host(`pihole.lhr1.jakerob.pro`)"
      service: pihole-prod-1
      tls:
        certresolver: cloudflare

  services:
    pihole-prod-1:
      loadBalancer:
        servers:
          - url: http://192.168.42.11
