http:
  services:
    lhr1-tunnel:
      loadBalancer:
        servers:
          - url: http://100.89.27.79

    slc1-tunnel:
      loadBalancer:
        servers:
          - url: http://100.95.11.23

  routers:
    whoami-lhr1-http:
      entrypoints: web
      rule: "Host(`whoami-tunnel-lhr1.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: lhr1-tunnel
    whoami-lhr1-https:
      entrypoints: websecure
      rule: "Host(`whoami-tunnel-lhr1.jakerob.pro`)"
      service: lhr1-tunnel
      tls:
        certresolver: production

    whoami-slc1-http:
      entrypoints: web
      rule: "Host(`whoami-tunnel-slc1.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: slc1-tunnel
    whoami-slc1-https:
      entrypoints: websecure
      rule: "Host(`whoami-tunnel-slc1.jakerob.pro`)"
      service: slc1-tunnel
      tls:
        certresolver: production
    
    wordpress-personal-lhr1-http:
      entrypoints: web
      rule: "Host(`wordpress.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: lhr1-tunnel
    wordpress-personal-lhr1-https:
      entrypoints: websecure
      rule: "Host(`wordpress.jakerob.pro`)"
      service: lhr1-tunnel
      tls:
        certresolver: production
