http:
  services:
    lhr1-tunnel:
      loadBalancer:
        servers:
          - url: https://100.89.27.79

    slc1-tunnel:
      loadBalancer:
        servers:
          - url: http://100.95.11.23

  routers:
    # WHOAMI LHR1
    whoami-lhr1-http:
      entrypoints: web
      rule: "Host(`whoami-tunnel-lhr1.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: lhr1-tunnel
    whoami-lhr1-https:
      entrypoints: websecure
      rule: "Host(`whoami-tunnel-lhr1.jakerob.pro`)"
      service: lhr1-tunnel
      tls:
        certresolver: production

     # WHOAMI LHR1
    whoami2-lhr1-http:
      entrypoints: web
      rule: "Host(`whoami-tunnel2-lhr1.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: lhr1-tunnel
    whoami2-lhr1-https:
      entrypoints: websecure
      rule: "Host(`whoami-tunnel2-lhr1.jakerob.pro`)"
      service: lhr1-tunnel
      tls:
        certresolver: synced

    # WHOAMI SLC1
    whoami-slc1-http:
      entrypoints: web
      rule: "Host(`whoami-tunnel-slc1.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: slc1-tunnel
    whoami-slc1-https:
      entrypoints: websecure
      rule: "Host(`whoami-tunnel-slc1.jakerob.pro`)"
      service: slc1-tunnel
      tls:
        certresolver: production

    # WORDPRESS PERSONAL LHR1
    wordpress-personal-lhr1-http:
      entrypoints: web
      rule: "Host(`wordpress.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: lhr1-tunnel
    wordpress-personal-lhr1-https:
      entrypoints: websecure
      rule: "Host(`wordpress.jakerob.pro`)"
      service: lhr1-tunnel
      tls:
        certresolver: production
