http:
  services:
    lhr1-tunnel:
      loadBalancer:
        servers:
          - url: https://100.89.27.79

    slc1-tunnel:
      loadBalancer:
        servers:
          - url: http://100.95.11.23

  routers:
    # WHOAMI LHR1
    whoami-blank-lhr1-http:
      entrypoints: web
      rule: "Host(`whoami.lhr1.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: lhr1-tunnel
    whoami-blank-lhr1-https:
      entrypoints: websecure
      rule: "Host(`whoami.lhr1.jakerob.pro`)"
      service: lhr1-tunnel
      tls: true

    immich-lhr1-http:
      entrypoints: web
      rule: "Host(`photos.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: lhr1-tunnel
    immich-lhr1-https:
      entrypoints: websecure
      rule: "Host(`photos.jakerob.pro`)"
      service: lhr1-tunnel
      tls: true

    jellyfin-lhr1-http:
      entrypoints: web
      rule: "Host(`jellyfin.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: lhr1-tunnel
    jellyfin-lhr1-https:
      entrypoints: websecure
      rule: "Host(`jellyfin.jakerob.pro`)"
      service: lhr1-tunnel
      tls: true

    karakeep-lhr1-http:
      entrypoints: web
      rule: "Host(`karakeep.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: lhr1-tunnel
    karakeep-lhr1-https:
      entrypoints: websecure
      rule: "Host(`karakeep.jakerob.pro`)"
      service: lhr1-tunnel
      tls: true

    authentik-lhr1-http:
      entrypoints: web
      rule: "Host(`authentik.lhr1.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: lhr1-tunnel
    authentik-lhr1-https:
      entrypoints: websecure
      rule: "Host(`authentik.lhr1.jakerob.pro`)"
      service: lhr1-tunnel
      tls: true

    # WHOAMI SLC1
    # whoami-slc1-http:
    #   entrypoints: web
    #   rule: "Host(`whoami-tunnel-slc1.jakerob.pro`)"
    #   middlewares:
    #     - websecure-redirect-permanent@file
    #   service: slc1-tunnel
    # whoami-slc1-https:
    #   entrypoints: websecure
    #   rule: "Host(`whoami-tunnel-slc1.jakerob.pro`)"
    #   service: slc1-tunnel
    #   tls:
    #     certresolver: production

    # # WORDPRESS PERSONAL LHR1
    # wordpress-personal-lhr1-http:
    #   entrypoints: web
    #   rule: "Host(`wordpress.jakerob.pro`)"
    #   middlewares:
    #     - websecure-redirect-permanent@file
    #   service: lhr1-tunnel
    # wordpress-personal-lhr1-https:
    #   entrypoints: websecure
    #   rule: "Host(`wordpress.jakerob.pro`)"
    #   service: lhr1-tunnel
    #   tls:
    #     certresolver: production
