---
name: traefik

networks:
  frontend:
    external: true
  internal:
    external: false
  tunnel:
    external: true

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik-prod-1
    user: 1000:1000
    ports:
      - 192.168.42.16:80:80
      - 192.168.42.16:443:443
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    networks:
      - frontend
      - internal
    labels:
      traefik.enable: true
      traefik.http.services.traefik-prod-1.loadBalancer.server.port: 8080
      traefik.http.routers.traefik-prod-1-http.entrypoints: web
      traefik.http.routers.traefik-prod-1-http.rule: Host(`traefik.lhr1.jakerob.pro`)
      traefik.http.routers.traefik-prod-1-http.middlewares: websecure-redirect-permanent@file
      traefik.http.routers.traefik-prod-1-https.entrypoints: websecure
      traefik.http.routers.traefik-prod-1-https.rule: Host(`traefik.lhr1.jakerob.pro`)
      traefik.http.routers.traefik-prod-1-https.tls: true
      traefik.http.routers.traefik-prod-1-https.tls.certresolver: cloudflare
    restart: unless-stopped

  traefik-tunnel:
    image: traefik:v3.0
    container_name: traefik-tunnel
    ports:
      # Bind on Tailscale interface only
      - 100.89.27.79:80:80
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./config-tunnel/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config-tunnel/conf/:/etc/traefik/conf/
    networks:
      - tunnel
      - internal
    labels:
      traefik.enable: true
      traefik.http.services.traefiktunnel-prod-1.loadBalancer.server.port: 8080
      traefik.http.routers.traefiktunnel-prod-1-http.entrypoints: web
      traefik.http.routers.traefiktunnel-prod-1-http.rule: Host(`traefik-tunnel.lhr1.jakerob.pro`)
      traefik.http.routers.traefiktunnel-prod-1-http.middlewares: websecure-redirect-permanent@file
      traefik.http.routers.traefiktunnel-prod-1-https.entrypoints: websecure
      traefik.http.routers.traefiktunnel-prod-1-https.rule: Host(`traefik-tunnel.lhr1.jakerob.pro`)
      traefik.http.routers.traefiktunnel-prod-1-https.tls: true
      traefik.http.routers.traefiktunnel-prod-1-https.tls.certresolver: cloudflare
    restart: unless-stopped
    
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: traefik-socket-proxy
    networks:
      - internal
    environment:
      - ALLOW_START=0 #optional
      - ALLOW_STOP=0 #optional
      - ALLOW_RESTARTS=0 #optional
      - AUTH=0 #optional
      - BUILD=0 #optional
      - COMMIT=0 #optional
      - CONFIGS=0 #optional
      - CONTAINERS=1 #optional
      - DISABLE_IPV6=0 #optional
      - DISTRIBUTION=0 #optional
      - EVENTS=1 #optional
      - EXEC=0 #optional
      - IMAGES=0 #optional
      - INFO=0 #optional
      - NETWORKS=1 #optional
      - NODES=0 #optional
      - PING=1 #optional
      - POST=0 #optional
      - PLUGINS=0 #optional
      - SECRETS=0 #optional
      - SERVICES=1 #optional
      - SESSION=0 #optional
      - SWARM=0 #optional
      - SYSTEM=0 #optional
      - TASKS=1 #optional
      - VERSION=1 #optional
      - VOLUMES=0 #optional
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run

  whoami:
    image: traefik/whoami
    container_name: whoami-prod-1
    networks:
      - frontend
    security_opt:
      - no-new-privileges:true
    command: --verbose
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.whoami-prod-1-http.entrypoints: web
      traefik.http.routers.whoami-prod-1-http.rule: Host(`whoami.lhr1.jakerob.pro`)
      traefik.http.routers.whoami-prod-1-http.middlewares: websecure-redirect-permanent@file
      traefik.http.routers.whoami-prod-1-https.entrypoints: websecure
      traefik.http.routers.whoami-prod-1-https.rule: Host(`whoami.lhr1.jakerob.pro`)
      traefik.http.routers.whoami-prod-1-https.tls: true
      traefik.http.routers.whoami-prod-1-https.tls.certresolver: cloudflare

  whoami-tunnel:
    image: traefik/whoami
    container_name: whoami-tunnel
    networks:
      - tunnel
    security_opt:
      - no-new-privileges:true
    command: --verbose
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.tunnel-external: "true"
      traefik.http.routers.whoamitunnel-prod-1-http.entrypoints: web
      traefik.http.routers.whoamitunnel-prod-1-http.rule: Host(`whoami-tunnel-lhr1.jakerob.pro`)
