---
networks:
  frontend:
    external: true

volumes:
  portainer-data:
    driver: local

services:
  portainer:
    image: portainer/portainer-ce:2.19.4-alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.services.portainer-prod-1.loadbalancer.server.port: "9000"
      traefik.http.services.portainer-prod-1.loadbalancer.server.scheme: "http"
      traefik.http.routers.portainer-prod-1-http.entrypoints: "web"
      traefik.http.routers.portainer-prod-1-http.rule: "Host(`portainer.lhr1.jakerob.pro`)"
      traefik.http.routers.portainer-prod-1-https.entrypoints: "websecure"
      traefik.http.routers.portainer-prod-1-https.rule: "Host(`portainer.lhr1.jakerob.pro`)"
      traefik.http.routers.portainer-prod-1-https.tls: "true"
      traefik.http.routers.portainer-prod-1-https.tls.certresolver: "cloudflare"
    networks:
      - frontend
