http:
  routers:
    minioweb-prod-1-http:
      entrypoints: web
      rule: "Host(`minio.slc1.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: minioweb-prod-1
    minioweb-prod-1-https:
      entrypoints: websecure
      rule: "Host(`minio.slc1.jakerob.pro`)"
      service: minioweb-prod-1
      tls:
        certresolver: cloudflare

    minioapi-prod-1-http:
      entrypoints: web
      rule: "Host(`minioapi.slc1.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: minioapi-prod-1
    minioapi-prod-1-https:
      entrypoints: websecure
      rule: "Host(`minioapi.slc1.jakerob.pro`)"
      service: minioapi-prod-1
      tls:
        certresolver: cloudflare

  services:
    minioweb-prod-1:
      loadBalancer:
        servers:
          - url: http://truenas.slc1.jakerob.pro:9002

    minioapi-prod-1:
      loadBalancer:
        servers:
          - url: http://truenas.slc1.jakerob.pro:9000
