---
networks:
  frontend:
    external: true
  backend:
    external: true
services:
  traefik:
    image: traefik:v2.11.0
    container_name: traefik-stage-1
    ports:
      - 81:80 # Demo is one higher
      - 444:443 # Demo is one higher
      # -- (Optional) Enable Dashboard, don't do in production
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
    # -- (Optional) When using Cloudflare as Cert Resolver
    environment:
      - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
    networks:
      - frontend
      - backend
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  whoami:
    image: traefik/whoami
    container_name: whoami-stage-1
    networks:
      - frontend
      - backend
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.whoami-demo-1-http.entrypoints: web
      traefik.http.routers.whoami-demo-1-http.rule: Host(`whoami.stage.lhr1.jakerob.pro`)
      traefik.http.routers.whoami-demo-1-https.entrypoints: websecure
      traefik.http.routers.whoami-demo-1-https.rule: Host(`whoami.stage.lhr1.jakerob.pro`)
