apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pull in the generic base
  - ../../base/infrastructure
patches:
  # Apply the Kind-specific values over the top
  - path: patch-cilium.yaml
    target:
      kind: HelmRelease
      name: cilium