---
name: calibre

networks:
  frontend:
    external: true

services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      # Edit to match your current timezone https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=UTC
    networks:
      - frontend
    volumes:
      - ./config:/config
      # This is an ingest dir, NOT a library one. Anything added here will be automatically added to your library according to the settings you have configured in CWA Settings page. All files placed here are REMOVED AFTER PROCESSING
      - ./ingest:/cwa-book-ingest
      - ./library:/calibre-library
    labels:
      traefik.enable: true
      traefik.http.routers.calibre-prod-1-http.entrypoints: web
      traefik.http.routers.calibre-prod-1-http.rule: Host(`calibre.jakerob.pro`)
      traefik.http.routers.calibre-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.calibre-prod-1-https.entrypoints: websecure
      traefik.http.routers.calibre-prod-1-https.rule: Host(`calibre.jakerob.pro`)
      traefik.http.routers.calibre-prod-1-https.tls: true
      traefik.http.routers.calibre-prod-1-https.tls.certresolver: cloudflare
      traefik.http.services.calibre-prod-1.loadBalancer.server.port: 8083
