version: 2

global:
  forget:
    keep-monthly: 2 # keep 2 last monthly snapshots

backends:
  truenas:
    type: local
    path: /nfs/backups/restic
    key: stored_in_.autorestic.env

locations:
  media-management-config:
    from:
      - ~/homelab/media-management/slc1-node-3/config
    to:
      - truenas
    cron: '0 2 * * *' # Every day at 2 AM

  authentik-config:
    from:
      - ~/homelab/authentik/slc1-node-3/certs
      - ~/homelab/authentik/slc1-node-3/custom-templates
      - ~/homelab/authentik/slc1-node-3/media
    to:
      - truenas
    cron: '0 2 * * *'

  authentik-data:
    from:
      - ~/homelab/authentik/slc1-node-3/backups
    to:
      - truenas
    cron: '0 2 * * *'
    options:
      forget:
        keep-last: 5 # always keep at least 5 snapshots
