---
name: minio

networks:
  frontend:
    external: true

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: minio server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./data:/data
    networks:
      - frontend
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.minioweb-prod-1-http.entrypoints: web
      traefik.http.routers.minioweb-prod-1-http.rule: Host(`minio.lhr1.jakerob.pro`)
      traefik.http.routers.minioweb-prod-1-http.middlewares: websecure-redirect-permanent@file
      traefik.http.routers.minioweb-prod-1-http.service: minioweb-prod-1
      traefik.http.routers.minioweb-prod-1-https.entrypoints: websecure
      traefik.http.routers.minioweb-prod-1-https.rule: Host(`minio.lhr1.jakerob.pro`)
      traefik.http.routers.minioweb-prod-1-https.service: minioweb-prod-1
      traefik.http.routers.minioweb-prod-1-https.tls: true
      traefik.http.routers.minioweb-prod-1-https.tls.certresolver: cloudflare
      traefik.http.services.minioweb-prod-1.loadBalancer.server.port: 9001

      traefik.http.routers.minioapi-prod-1-http.entrypoints: web
      traefik.http.routers.minioapi-prod-1-http.rule: Host(`minioapi.lhr1.jakerob.pro`)
      traefik.http.routers.minioapi-prod-1-http.middlewares: websecure-redirect-permanent@file
      traefik.http.routers.minioapi-prod-1-http.service: minioapi-prod-1
      traefik.http.routers.minioapi-prod-1-https.entrypoints: websecure
      traefik.http.routers.minioapi-prod-1-https.rule: Host(`minioapi.lhr1.jakerob.pro`)
      traefik.http.routers.minioapi-prod-1-https.service: minioapi-prod-1
      traefik.http.routers.minioapi-prod-1-https.tls: true
      traefik.http.routers.minioapi-prod-1-https.tls.certresolver: cloudflare
      traefik.http.services.minioapi-prod-1.loadBalancer.server.port: 9000