---
all:
  hosts:
    #### PBJ ####
    # Raspberry Pi Model 3
    pbj-pi-1:
      ansible_user: ansible-robot
      ansible_host: pbj-pi-1.jakerob.pro

    pbj-node-1:
      ansible_user: ansible-robot
      ansible_host: pbj-node-1.jakerob.pro

    pbj-hv-1:
      ansible_user: ansible-robot
      ansible_host: pbj-hv-1.jakerob.pro

    pbj-storage-1:
      ansible_user: truenas_admin
      ansible_host: pbj-storage-1.jakerob.pro

    #### IAD1 ####

    iad1-node-1:
      ansible_user: jacobroberts
      ansible_host: iad1-vpn-node-1.jakerob.pro

    iad1-node-2:
      ansible_user: jacobroberts
      ansible_host: iad1-vpn-node-2.jakerob.pro

    iad1-node-3:
      ansible_user: jacobroberts
      ansible_host: iad1-vpn-node-3.jakerob.pro

    #### SLC1 ####

    slc1-hv-1:
      ansible_user: root
      ansible_host: slc1-hv-1.jakerob.pro

    slc1-node-3:
      ansible_user: jacobroberts
      ansible_host: slc1-node-3.jakerob.pro

    slc1-storage-1:
      ansible_user: admin
      ansible_host: slc1-storage-1.jakerob.pro

    # Raspberry Pi Model 3
    slc1-pi-1:
      ansible_user: jacobroberts
      ansible_host: slc1-pi-1.jakerob.pro

    #### SGU1 ####

    sgu1-hv-1:
      ansible_user: root
      ansible_host: sgu1-hv-1.jakerob.pro

    sgu1-node-1:
      ansible_user: jacobroberts
      ansible_host: sgu1-node-1.jakerob.pro

  children:
    bootstrap:
      hosts:
        pbj-node-1:

    docker:
      hosts:
        pbj-node-1:
        iad1-node-1:
        iad1-node-2:
        iad1-node-3:
        slc1-node-3:
        sgu1-node-1:

    example:
      hosts:
        pbj-pi-1:

    updatable_apt:
      hosts:
        pbj-pi-1:
        pbj-node-1:
        pbj-hv-1:
        iad1-node-1:
        # iad1-node-2:
        # iad1-node-3:
        slc1-hv-1:
        slc1-node-3:
        slc1-pi-1:
        sgu1-node-1:
    qemu:
      hosts:
        pbj-node-1:
        sgu1-node-1:
        slc1-node-3:

    pihole:
      hosts:
        pbj-pi-1:

    tailscale:
      hosts:
        pbj-node-1:

    nut_primary_pbj:
      hosts:
        pbj-pi-1:
    nut_clients_pbj:
      hosts:
        # pbj-storage-1: Truenas doesn't like to be configured by ansible
        pbj-hv-1:

    nut_primary_slc1:
      hosts:
        slc1-pi-1:
    nut_clients_slc1:
      hosts:
        # slc1-storage-1: Truenas doesn't like to be configured by ansible
        slc1-hv-1: