# This tunnel only uses http
http:
  services:
    lhr1-traefik:
      loadBalancer:
        servers:
          - url: https://traefik

  routers:
    # WHOAMI LHR1
    whoami-lhr1-https:
      entrypoints: websecure
      rule: "Host(`whoami.lhr1.jakerob.pro`)"
      service: lhr1-traefik
      tls: true
