http:
  routers:
    whoamitunnel2-prod-1-http:
      entrypoints: web
      rule: "Host(`whoami-tunnel2-lhr1.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: whoami-tunnel-2
    whoamitunnel2-prod-1-https:
      entrypoints: websecure
      rule: "Host(`whoami-tunnel2-lhr1.jakerob.pro`)"
      service: whoami-tunnel-2
      tls:
        certResolver: cloudflare

  services:
    whoami-tunnel-2:
      loadBalancer:
        servers:
          - url: http://whoami-tunnel-2
