tls:
  certificates:
    - certFile: /traefik/static-certs-pbj/whoami-tunnel.pbj.jakerob.pro/certificate.crt
      keyFile: /traefik/static-certs-pbj/whoami-tunnel.pbj.jakerob.pro/privatekey.key
    - certFile: /traefik/static-certs-pbj/auth.jakerob.pro/certificate.crt
      keyFile: /traefik/static-certs-pbj/auth.jakerob.pro/privatekey.key
    - certFile: /traefik/static-certs-pbj/photos.jakerob.pro/certificate.crt
      keyFile: /traefik/static-certs-pbj/photos.jakerob.pro/privatekey.key
    - certFile: /traefik/static-certs-pbj/jellyfin.jakerob.pro/certificate.crt
      keyFile: /traefik/static-certs-pbj/jellyfin.jakerob.pro/privatekey.key
    - certFile: /traefik/static-certs-pbj/karakeep.jakerob.pro/certificate.crt
      keyFile: /traefik/static-certs-pbj/karakeep.jakerob.pro/privatekey.key
    - certFile: /traefik/static-certs-pbj/calibre.jakerob.pro/certificate.crt
      keyFile: /traefik/static-certs-pbj/calibre.jakerob.pro/privatekey.key
    - certFile: /traefik/static-certs-slc1/whoami-tunnel.slc1.jakerob.pro/certificate.crt
      keyFile: /traefik/static-certs-slc1/whoami-tunnel.slc1.jakerob.pro/privatekey.key
    - certFile: /traefik/static-certs-slc1/auth.autovation.com/certificate.crt
      keyFile: /traefik/static-certs-slc1/auth.autovation.com/privatekey.key
    - certFile: /traefik/static-certs-slc1/photos.autovation.com/certificate.crt
      keyFile: /traefik/static-certs-slc1/photos.autovation.com/privatekey.key
