http:
  services:
    pbj-tunnel:
      loadBalancer:
        servers:
          - url: https://pbj-node-1.vpn.jakerob.pro

    slc1-tunnel:
      loadBalancer:
        servers:
          - url: https://slc1-node-3.vpn.jakerob.pro

  routers:
    # WHOAMI pbj
    whoami-tunnel-pbj-http:
      entrypoints: web
      rule: "Host(`whoami-tunnel.pbj.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: pbj-tunnel
    whoami-tunnel-pbj-https:
      entrypoints: websecure
      rule: "Host(`whoami-tunnel.pbj.jakerob.pro`)"
      service: pbj-tunnel
      tls: true

    immich-pbj-http:
      entrypoints: web
      rule: "Host(`photos.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: pbj-tunnel
    immich-pbj-https:
      entrypoints: websecure
      rule: "Host(`photos.jakerob.pro`)"
      service: pbj-tunnel
      tls: true

    jellyfin-pbj-http:
      entrypoints: web
      rule: "Host(`jellyfin.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: pbj-tunnel
    jellyfin-pbj-https:
      entrypoints: websecure
      rule: "Host(`jellyfin.jakerob.pro`)"
      service: pbj-tunnel
      tls: true

    karakeep-pbj-http:
      entrypoints: web
      rule: "Host(`karakeep.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: pbj-tunnel
    karakeep-pbj-https:
      entrypoints: websecure
      rule: "Host(`karakeep.jakerob.pro`)"
      service: pbj-tunnel
      tls: true

    calibre-pbj-http:
      entrypoints: web
      rule: "Host(`calibre.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: pbj-tunnel
    calibre-pbj-https:
      entrypoints: websecure
      rule: "Host(`calibre.jakerob.pro`)"
      service: pbj-tunnel
      tls: true

    pocket-id-pbj-http:
      entrypoints: web
      rule: "Host(`pocket-id.lhr1.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: pbj-tunnel
    pocket-id-pbj-https:
      entrypoints: websecure
      rule: "Host(`pocket-id.lhr1.jakerob.pro`)"
      service: pbj-tunnel
      tls: true

    whoami-tunnel-slc1-http:
      entrypoints: web
      rule: "Host(`whoami-tunnel.slc1.jakerob.pro`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: slc1-tunnel
    whoami-tunnel-slc1-https:
      entrypoints: websecure
      rule: "Host(`whoami-tunnel.slc1.jakerob.pro`)"
      service: slc1-tunnel
      tls: true

    pocket-id-slc1-http:
      entrypoints: web
      rule: "Host(`auth.autovation.com`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: slc1-tunnel
    pocket-id-slc1-https:
      entrypoints: websecure
      rule: "Host(`auth.autovation.com`)"
      service: slc1-tunnel
      tls: true

    photos-slc1-http:
      entrypoints: web
      rule: "Host(`photos.autovation.com`)"
      middlewares:
        - websecure-redirect-permanent@file
      service: slc1-tunnel
    photos-slc1-https:
      entrypoints: websecure
      rule: "Host(`photos.autovation.com`)"
      service: slc1-tunnel
      tls: true

    # WHOAMI SLC1
    # whoami-slc1-http:
    #   entrypoints: web
    #   rule: "Host(`whoami-tunnel-slc1.jakerob.pro`)"
    #   middlewares:
    #     - websecure-redirect-permanent@file
    #   service: slc1-tunnel
    # whoami-slc1-https:
    #   entrypoints: websecure
    #   rule: "Host(`whoami-tunnel-slc1.jakerob.pro`)"
    #   service: slc1-tunnel
    #   tls:
    #     certresolver: production

    # # WORDPRESS PERSONAL pbj
    # wordpress-personal-pbj-http:
    #   entrypoints: web
    #   rule: "Host(`wordpress.jakerob.pro`)"
    #   middlewares:
    #     - websecure-redirect-permanent@file
    #   service: pbj-tunnel
    # wordpress-personal-pbj-https:
    #   entrypoints: websecure
    #   rule: "Host(`wordpress.jakerob.pro`)"
    #   service: pbj-tunnel
    #   tls:
    #     certresolver: production
