---
networks:
  frontend:
    external: true
  backend:
    external: true

services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    command: --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    networks:
      - frontend
      - backend
    ports:
      - 12345:12345
    volumes:
      - ./config/config.alloy:/etc/alloy/config.alloy
