---
name: jellyfin

networks:
  frontend:
    external: true
  backend:
    external: true

services:
  jellyfin:
    image: jellyfin/jellyfin:10.9.2
    container_name: jellyfin
    user: 1000:1000
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /nfs/jellydata:/jellydata
    restart: 'unless-stopped'
    networks:
      - frontend
      - backend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - JELLYFIN_PublishedServerUrl=https://jellyfin.slc1.jakerob.pro
    labels:
      traefik.enable: "true"
      traefik.http.services.jellyfin-prod-1.loadBalancer.server.port: 8096
      traefik.http.routers.jellyfin-prod-1-http.entrypoints: web
      traefik.http.routers.jellyfin-prod-1-http.rule: Host(`jellyfin.slc1.jakerob.pro`)
      traefik.http.routers.jellyfin-prod-1-http.middlewares: websecure-redirect-permanent@file
      traefik.http.routers.jellyfin-prod-1-https.entrypoints: websecure
      traefik.http.routers.jellyfin-prod-1-https.rule: Host(`jellyfin.slc1.jakerob.pro`)
      traefik.http.routers.jellyfin-prod-1-https.tls: true
      traefik.http.routers.jellyfin-prod-1-https.tls.certresolver: cloudflare
