---
networks:
  backend:
    external: true
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - $DOCKERDIR/appdata/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
