---
name: semaphore

volumes:
  semaphore_data:
    driver: local
  semaphore_config:
    driver: local
  semaphore_tmp:
    driver: local
  ts_state:
    driver: local

networks:
  frontend:
    external: true

services:
  semaphore:
    image: semaphoreui/semaphore:v2.18.27
    environment:
      SEMAPHORE_DB_DIALECT: sqlite
      SEMAPHORE_ADMIN: ${SEMAPHORE_ADMIN}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL}
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY_ENCRYPTION}
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    network_mode: "service:tailscale"
    logging:
      driver: local
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
    volumes:
      - semaphore_data:/var/lib/semaphore
      - semaphore_config:/etc/semaphore
      - semaphore_tmp:/tmp/semaphore

  tailscale:
    container_name: tailscale-semaphore
    image: docker.io/tailscale/tailscale:v1.98
    hostname: semaphore-ansible-robot
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
      - TS_EXTRA_ARGS=--accept-routes
    volumes:
      - ts_state:/var/lib/tailscale
    cap_add:
      - net_admin
      - net_raw
    security_opt:
      - no-new-privileges:true
    networks:
      - frontend
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.services.semaphore-prod-1.loadbalancer.server.port: 3000
      traefik.http.routers.semaphore-prod-1-http.entrypoints: web
      traefik.http.routers.semaphore-prod-1-http.rule: Host(`${SEMAPHORE_URL}`)
      traefik.http.routers.semaphore-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.semaphore-prod-1-https.entrypoints: websecure
      traefik.http.routers.semaphore-prod-1-https.rule: Host(`${SEMAPHORE_URL}`)
      traefik.http.routers.semaphore-prod-1-https.tls: true
      traefik.http.routers.semaphore-prod-1-https.tls.certresolver: cloudflare
