apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: homepage-secrets
  namespace: homepage
spec:
  syncConfig:
    resyncInterval: 1m
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectId: f3732b81-3a85-430d-a547-43b85c363ad6
        envSlug: prod
        secretsPath: /slc1-node-3/homepage
        recursive: true
  managedSecretReference:
    secretName: homepage-secrets
    secretNamespace: homepage
    creationPolicy: Owner