---
name: media-management

networks:
  frontend:
    external: true

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    restart: unless-stopped
    ports:
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
    environment:
      PUID: '1000'
      PGID: '1000'
    networks:
      - frontend
    volumes:
      - ./config:/config
      - /media/jellydata:/jellydata
    labels:
      traefik.enable: true
      traefik.http.services.syncthing-prod-1.loadbalancer.server.port: '8384'
      traefik.http.routers.syncthing-prod-1-http.entrypoints: web
      traefik.http.routers.syncthing-prod-1-http.rule: Host(`syncthing.sgu1.jakerob.pro`)
      traefik.http.routers.syncthing-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.syncthing-prod-1-https.entrypoints: websecure
      traefik.http.routers.syncthing-prod-1-https.rule: Host(`syncthing.sgu1.jakerob.pro`)
      traefik.http.routers.syncthing-prod-1-https.tls: true
      traefik.http.routers.syncthing-prod-1-https.tls.certresolver: cloudflare
