---
# Environment overrides for iad1-node-1 (direct socket)
services:
  portainer:
    labels:
      traefik.http.routers.portainer-prod-1-http.rule: Host(`${PORTAINER_URL:-portainer.iad1vpn.jakerob.pro}`)
      traefik.http.routers.portainer-prod-1-https.rule: Host(`${PORTAINER_URL:-portainer.iad1vpn.jakerob.pro}`)
