---

name: socialsignal

networks:
  frontend:
    external: true

services:
  socialsignal:
    image: ghcr.io/jacob-roberts/social-signal-backend:0.0.1-alpha1
    container_name: socialsignal
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - frontend
    labels:
      traefik.enable: true
      traefik.external: true
      traefik.docker.network: frontend
      traefik.http.services.socialsignal.loadBalancer.server.port: 8080
      traefik.http.routers.socialsignal-http.entrypoints: web
      traefik.http.routers.socialsignal-http.rule: Host(`api.socialsignal.jakerob.pro`)
      traefik.http.routers.socialsignal-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.socialsignal-https.entrypoints: websecure
      traefik.http.routers.socialsignal-https.rule: Host(`api.socialsignal.jakerob.pro`)
      traefik.http.routers.socialsignal-https.tls: true
      traefik.http.routers.socialsignal-https.tls.certresolver: production
