---

name: socialsignal

networks:
  frontend:
    external: true
  internal:
    external: false

services:
  socialsignal:
    image: ghcr.io/jacob-roberts/social-signal-backend:0.0.1-alpha5
    container_name: socialsignal
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - frontend
      - internal
    environment:
      APP_BASE_URL: "https://socialsignal.jakerob.pro"
      JWKS_URL: "https://socialsignal.jakerob.pro/api/auth/jwks"
      DATABASE_TYPE: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: social_signal
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: social_signal_db
      DATABASE_SSLMODE: disable
    labels:
      traefik.enable: true
      traefik.external: true
      traefik.docker.network: frontend
      traefik.http.services.socialsignal.loadBalancer.server.port: 8080
      traefik.http.routers.socialsignal-http.entrypoints: web
      traefik.http.routers.socialsignal-http.rule: Host(`api.socialsignal.jakerob.pro`)
      traefik.http.routers.socialsignal-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.socialsignal-https.entrypoints: websecure
      traefik.http.routers.socialsignal-https.rule: Host(`api.socialsignal.jakerob.pro`)
      traefik.http.routers.socialsignal-https.tls: true
      traefik.http.routers.socialsignal-https.tls.certresolver: production

  postgres:
    image: postgres:15-alpine
    networks:
      - internal
    restart: unless-stopped
    environment:
      - POSTGRES_USER=social_signal
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=social_signal_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    networks:
      - internal
    restart: unless-stopped
    environment:
      - MYSQL_USER=social_signal
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=social_signal_db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  postgres_data:
  mysql_data: