---
name: homeassistant

networks:
  frontend:
    external: true

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2025.1.2
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    # devices:
    #   - /dev/ttyACMO
    privileged: true
    labels:
      traefik.enable: true
      traefik.http.services.homeassistant-prod-1.loadbalancer.server.port: "8123"
      traefik.http.services.homeassistant-prod-1.loadbalancer.server.scheme: "http"
      traefik.http.routers.homeassistant-prod-1-http.entrypoints: web
      traefik.http.routers.homeassistant-prod-1-http.rule: Host(`homeassistant.lhr1.jakerob.pro`)
      traefik.http.routers.homeassistant-prod-1-http.middlewares: websecure-redirect-permanent@file
      traefik.http.routers.homeassistant-prod-1-https.entrypoints: "websecure"
      traefik.http.routers.homeassistant-prod-1-https.rule: "Host(`homeassistant.lhr1.jakerob.pro`)"
      traefik.http.routers.homeassistant-prod-1-https.tls: "true"
      traefik.http.routers.homeassistant-prod-1-https.tls.certresolver: "cloudflare"
    networks:
      - frontend
    restart: unless-stopped