---
- hosts: docker
  become: true
  vars:
    created_username: jacobroberts

  tasks:
    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/keyrings/docker.gpg

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        filename: docker
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename | lower }} stable
        state: present

    - name: Install docker engine
      ansible.builtin.apt:
        name:
          - docker-ce
        update_cache: true

    - name: Add the user "{{ created_username }}" to group 'docker'
      ansible.builtin.user:
        name: "{{ created_username }}"
        groups: docker
        append: yes
