version: 2

global:
  forget:
    keep-monthly: 2 # keep 2 last monthly snapshots

backends:
  truenas:
    type: local
    path: /nfs/backups/restic
    key: stored_in_.autorestic.env

locations:
  media-management-config:
    from:
      - ~/homelab/media-management/slc1-node-3/config
    to:
      - truenas
    cron: '0 2 * * *' # Every day at 2 AM

  immich:
    from:
      - ~/homelab/immich/slc1-node-3/database
      - ~/homelab/immich/slc1-node-3/model-cache
    to:
      - truenas
    cron: '0 2 * * *'
