---

services:
  loki:
    image: grafana/loki:2.9.7
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.7
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
