version: 2

global:
  forget:
    keep-monthly: 2 # keep 2 last monthly snapshots

backends:
  slctruenas:
    type: s3
    path: https://minioapi.slc1.jakerob.pro/lhr1-backups
    env:
      AWS_ACCESS_KEY_ID: stored_in_.autorestic.env
      AWS_SECRET_ACCESS_KEY: stored_in_.autorestic.env

  backblaze:
    type: s3
    path: s3.us-west-002.backblazeb2.com/lhr1-backups
    env:
      AWS_ACCESS_KEY_ID: stored_in_.autorestic.env
      AWS_SECRET_ACCESS_KEY: stored_in_.autorestic.env

locations:
  media-management-config:
    from:
      - ~/homelab/media-management/lhr1-node-1/bazarr-config
      - ~/homelab/media-management/lhr1-node-1/gluetun-config
      - ~/homelab/media-management/lhr1-node-1/prowlarr-config
      - ~/homelab/media-management/lhr1-node-1/qbittorrent-config
      - ~/homelab/media-management/lhr1-node-1/radarr-config
      - ~/homelab/media-management/lhr1-node-1/sabnzbd-config
      - ~/homelab/media-management/lhr1-node-1/sonarr-config
      - ~/homelab/media-management/lhr1-node-1/syncthing-config
    to:
      - slctruenas
      - backblaze
    cron: '0 2 * * *' # Every day at 2 AM

  authentik-config:
    from:
      - ~/homelab/authentik/lhr1-node-1/certs
      - ~/homelab/authentik/lhr1-node-1/custom-templates
      - ~/homelab/authentik/lhr1-node-1/media
    to:
      - slctruenas
      - backblaze
    cron: '0 2 * * *'

  authentik-data:
    from:
      - ~/homelab/authentik/lhr1-node-1/backups
    to:
      - slctruenas
      - backblaze
    cron: '0 2 * * *'
    options:
      forget:
        keep-last: 5 # always keep at least 5 snapshots

  immich:
    from:
      - ~/homelab/immich/lhr1-node-1/database
      - ~/homelab/immich/lhr1-node-1/immich
      - ~/homelab/immich/lhr1-node-1/model-cache
    to:
      - slctruenas
    cron: '0 2 * * *'

  nextcloud-db:
    from: nextcloud-database
    type: volume
    to:
      - slctruenas

  nextcloud-files:
    from:
      - ~/homelab/nextcloud/lhr1-node-1/data
    to:
      - slctruenas
