---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  infisicalAuthRef:
    name: infisical-auth
    namespace: infisical
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectId: f3732b81-3a85-430d-a547-43b85c363ad6
      environmentSlug: prod
      secretPath: /pbj/k8s
  targets:
    - name: cloudflare-api-token
      namespace: cert-manager
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          api-token: "{{ .CLOUDFLARE_API_TOKEN.Value }}"