---

name: dns

services:
# Run Pihole baremetal 


  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    environment:
    - PRIMARY=http://pihole.lhr1.jakerob.pro|${PIHOLE_PASSWORD}
    - REPLICAS=http://pihole2.lhr1.jakerob.pro|${PIHOLE_PASSWORD}
    - FULL_SYNC=true
    - CRON=0 * * * *