---
name: matrix

networks:
  frontend:
    external: true
  internal:
    external: false
    name: matrix_internal

services:
  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    depends_on:
      - db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - frontend
      - internal
    # See the readme for a full documentation of the environment settings
    # NOTE: You must edit homeserver.yaml to use postgres, it defaults to sqlite
    environment:
      TZ: "Europe/London"
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
      UID: 1002
      GID: 1002
    volumes:
      - ./data:/data
    labels:
      traefik.enable: true
      traefik.external: true
      traefik.http.routers.synapse-prod-1-http.entryPoints: web
      traefik.http.routers.synapse-prod-1-http.rule: Host(`matrix.jakerob.pro`)
      traefik.http.routers.synapse-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.synapse-prod-1-https.entryPoints: websecure
      traefik.http.routers.synapse-prod-1-https.rule: Host(`matrix.jakerob.pro`)
      traefik.http.routers.synapse-prod-1-https.tls: true
      traefik.http.routers.synapse-prod-1-https.tls.certresolver: production
      traefik.http.services.synapse-prod-1.loadBalancer.server.port: 8008

  db:
    image: docker.io/postgres:15-alpine
    security_opt:
      - no-new-privileges:true
    networks:
      - internal
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-synapse}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # ensure the database gets created correctly
      # https://element-hq.github.io/synapse/latest/postgres.html#set-up-database
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./db-data:/var/lib/postgresql/data
