---
name: uptimekuma

networks:
  frontend:
    external: true

services:
  uptimekuma:
    image: louislam/uptime-kuma:1.23.13-alpine
    container_name: uptimekuma
    volumes:
      - ./data:/app/data
    security_opt:
      - no-new-privileges:true
    labels:
      traefik.enable: true
      traefik.http.routers.uptimekuma-prod-1-http.entrypoints: web
      traefik.http.routers.uptimekuma-prod-1-http.rule: Host(`uptime.lhr1.jakerob.pro`)
      traefik.http.routers.uptimekuma-prod-1-http.middlewares: websecure-redirect-permanent@file
      traefik.http.routers.uptimekuma-prod-1-https.entrypoints: websecure
      traefik.http.routers.uptimekuma-prod-1-https.rule: Host(`uptime.lhr1.jakerob.pro`)
      traefik.http.routers.uptimekuma-prod-1-https.tls: true
      traefik.http.routers.uptimekuma-prod-1-https.tls.certresolver: cloudflare
    networks:
      - frontend
    restart: unless-stopped
