---
name: grafana-alloy

networks:
  frontend:
    external: true

services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    networks:
      - frontend
    ports:
      - 100.70.105.44:12345:12345
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/etc/os-release:ro
      - ./config/config.alloy:/etc/alloy/config.alloy
