---
name: homebox

# NOTE: THIS PROJECT IS ARCHIVED

networks:
  frontend:
    external: true

volumes:
  homebox-data:
    name: homebox-data
    external: true

services:
  homebox:
    image: ghcr.io/hay-kot/homebox:v0.10.3
    container_name: homebox
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      HBOX_LOG_LEVEL: info
      HBOX_LOG_FORMAT: text
      HBOX_WEB_MAX_UPLOAD_SIZE: '10'
    networks:
      - frontend
    volumes:
      - homebox-data:/data/
    labels:
      traefik.enable: true
      traefik.external: true
      traefik.http.services.homebox-prod-1.loadBalancer.server.port: 7745
      traefik.http.routers.homebox-prod-1-http.entrypoints: web
      traefik.http.routers.homebox-prod-1-http.rule: Host(`homebox.jakerob.pro`)
      traefik.http.routers.homebox-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.homebox-prod-1-https.entrypoints: websecure
      traefik.http.routers.homebox-prod-1-https.rule: Host(`homebox.jakerob.pro`)
      traefik.http.routers.homebox-prod-1-https.tls: true
      traefik.http.routers.homebox-prod-1-https.tls.certresolver: production

