apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/whoami
  - ../base/podinfo
  - ../base/beszel
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
      namespace: podinfo
      name: podinfo
  - path: podinfo-values.yaml
    target:
      kind: HTTPRoute
      namespace: whoami
      name: whoami
  - path: beszel-values.yaml
    target:
      kind: HTTPRoute
      namespace: beszel
      name: beszel
