---
networks:
  dokploy-network:
    driver: overlay
    attachable: true
    name: dokploy-network
    external: true

services:
  whoami-swarm-internal:
    image: docker.io/traefik/whoami:latest
    command: "--verbose"
    networks:
      - dokploy-network
    labels:
      traefik.enable: "true"
      traefik.docker.network: dokploy-network
      traefik.http.routers.whoamiswarminternal-prod-1-http.entrypoints: web
      traefik.http.routers.whoamiswarminternal-prod-1-http.rule: Host(`whoami-swarm.iad1vpn.jakerob.pro`)
      traefik.http.routers.whoamiswarminternal-prod-1-https.entrypoints: websecure
      traefik.http.routers.whoamiswarminternal-prod-1-https.rule: Host(`whoami-swarm.iad1vpn.jakerob.pro`)
      traefik.http.routers.whoamiswarminternal-prod-1-https.tls: "true"
      traefik.http.routers.whoamiswarminternal-prod-1-https.tls.certresolver: cloudflare
