---
- name: Check to ensure all hosts have enough disk space
  hosts: "all"
  become: yes

  vars_files:
    - config-secrets.yaml

  vars:
    # See config-secrets.yaml
    #discord_webhook_url: DISCORD_WEBHOOK_URL_HERE

  tasks:
    - name: Get disk usage
      command: df -h
      register: disk_usage

    - name: Check disk space available
      shell: df -h / | awk 'NR==2 {print $5}'
      register: disk_usage

    # Send Discord message when disk space is over 80%
    - name: Send Discord message
      uri:
        url: "{{ discord_webhook_url }}"
        method: POST
        body_format: json
        body: '{"content": "Disk space on {{ inventory_hostname }} is above 80%!"}'
        headers:
          Content-Type: application/json
        status_code: 204
      when: disk_usage.stdout[:-1]|int > 80
