---
name: plausible

networks:
  frontend:
    external: true
  internal:
    external: false

services:
  plausible_db:
    # Plausible v2.0.0 was tested against PostgreSQL versions 12, 13, and 14
    # https://github.com/plausible/analytics/blob/v2.0.0/.github/workflows/elixir.yml#L16
    image: postgres:16-alpine
    container_name: plausible-db
    restart: unless-stopped
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      start_period: 1m

    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    networks:
      - internal
    volumes:
      - ./db-data:/var/lib/postgresql/data
  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    container_name: plausible-events-db
    restart: unless-stopped
    healthcheck:
      test: [CMD-SHELL, "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      start_period: 1m

    networks:
      - internal
    volumes:
      - ./event-data:/var/lib/clickhouse
      - ./event-logs:/var/log/clickhouse-server
      - ./clickhouse/logs.xml:/etc/clickhouse-server/config.d/logs.xml:ro
      # This makes ClickHouse bind to IPv4 only, since Docker doesn't enable IPv6 in bridge networks by default.
      # Fixes "Listen [::]:9000 failed: Address family for hostname not supported" warnings.
      - ./clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
      # This makes ClickHouse consume less resources, which is useful for small setups.
      # https://clickhouse.com/docs/en/operations/tips#using-less-than-16gb-of-ram
      - ./clickhouse/low-resources.xml:/etc/clickhouse-server/config.d/low-resources.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.1
    container_name: plausible
    command: "sh -c \"/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run\""
    depends_on:
      plausible_db:
        condition: service_healthy
      plausible_events_db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - TMPDIR=/var/lib/plausible/tmp
      - "BASE_URL=${BASE_URL:-https://plausible.iad1.jakerob.pro}"
      - "SECRET_KEY_BASE=${SECRET_KEY_BASE}"
      - "TOTP_VAULT_KEY=${TOTP_VAULT_KEY}"
      # - DISABLE_REGISTRATION
      # - ENABLE_EMAIL_VERIFICATION
      - "DATABASE_URL=postgres://postgres:${DATABASE_PASSWORD}@plausible_db:5432/plausible_db"
      - CLICKHOUSE_DATABASE_URL=http://plausible_events_db:8123/plausible_events_db
      - MAILER_ADAPTER=Bamboo.Mua
      - "MAILER_EMAIL=${MAILER_EMAIL}"
      - MAILER_NAME=plausible-analytics
      - "SMTP_HOST_ADDR=${SMTP_HOST_ADDR}"
      - "SMTP_HOST_PORT=${SMTP_HOST_PORT}"
      - "SMTP_USER_NAME=${SMTP_USER_NAME}"
      - "SMTP_USER_PWD=${SMTP_USER_PWD}"
    networks:
      - frontend
      - internal
    volumes:
      - ./plausible-data:/var/lib/plausible
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    labels:
      traefik.enable: true
      traefik.external: true
      traefik.docker.network: frontend
      traefik.http.routers.plausible-prod-1-http.entrypoints: web
      traefik.http.routers.plausible-prod-1-http.rule: Host(`plausible.iad1.jakerob.pro`)
      traefik.http.routers.plausible-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.plausible-prod-1-https.entrypoints: websecure
      traefik.http.routers.plausible-prod-1-https.rule: Host(`plausible.iad1.jakerob.pro`)
      traefik.http.routers.plausible-prod-1-https.tls: true
      traefik.http.routers.plausible-prod-1-https.tls.certresolver: production
      traefik.http.services.plausible-prod-1.loadbalancer.server.port: '8000'
