---
name: plausible

networks:
  frontend:
    external: true
  internal:
    external: false

services:
  plausible_db:
    # Plausible v2.0.0 was tested against PostgreSQL versions 12, 13, and 14
    # https://github.com/plausible/analytics/blob/v2.0.0/.github/workflows/elixir.yml#L16
    image: postgres:14-alpine
    container_name: plausible-db
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 1m

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    container_name: plausible-events-db
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./event-data:/var/lib/clickhouse
      - ./event-logs:/var/log/clickhouse-server
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O - http://127.0.0.1:8123/ping || exit 1"]
      start_period: 1m

  plausible:
    image: plausible/analytics:v2.0
    container_name: plausible
    restart: unless-stopped
    command: sh -c "/entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      plausible_db:
        condition: service_healthy
      plausible_events_db:
        condition: service_healthy
    networks:
      - frontend
      - internal
    volumes:
      - ./plausible-data:/var/lib/plausible
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - TMPDIR=/var/lib/plausible/tmp
      - BASE_URL=${BASE_URL:-https://plausible.iad1.jakerob.pro}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - TOTP_VAULT_KEY=${TOTP_VAULT_KEY}
      # - DISABLE_REGISTRATION
      # - ENABLE_EMAIL_VERIFICATION
      - DATABASE_URL=postgres://postgres:${DATABASE_PASSWORD}@plausible_db:5432/plausible_db
      - CLICKHOUSE_DATABASE_URL=http://plausible_events_db:8123/plausible_events_db
      - MAILER_EMAIL=${MAILER_EMAIL}
      - MAILER_NAME=plausible-analytics
      - SMTP_HOST_ADDR=${SMTP_HOST_ADDR}
      - SMTP_HOST_PORT=${SMTP_HOST_PORT}
      - SMTP_USER_NAME=${SMTP_USER_NAME}
      - SMTP_USER_PWD=${SMTP_USER_PWD}
      - SMTP_HOST_SSL_ENABLED=${SMTP_HOST_SSL_ENABLED}
    labels:
      traefik.enable: true
      traefik.external: true
      traefik.docker.network: frontend
      traefik.http.routers.plausible-prod-1-http.entrypoints: web
      traefik.http.routers.plausible-prod-1-http.rule: "Host(`plausible.iad1.jakerob.pro`)"
      traefik.http.routers.plausible-prod-1-http.middlewares: websecure-redirect-permanent@file
      traefik.http.routers.plausible-prod-1-https.entrypoints: websecure
      traefik.http.routers.plausible-prod-1-https.rule: "Host(`plausible.iad1.jakerob.pro`)"
      traefik.http.routers.plausible-prod-1-https.tls: true
      traefik.http.routers.plausible-prod-1-https.tls.certresolver: production
      traefik.http.services.plausible-prod-1.loadbalancer.server.port: "8000"
