---
name: karakeep

networks:
  frontend:
    external: true
  internal:
    external: false
    name: karakeep_internal

services:
  web:
    image: ghcr.io/karakeep-app/karakeep:release
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222

      # OPENAI_API_KEY: ...

      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      DATA_DIR: /data # DON'T CHANGE THIS
    networks:
      - frontend
      - internal
    labels:
      traefik.enable: true
      traefik.http.services.karakeep-prod-1.loadBalancer.server.port: 3000
      traefik.http.routers.karakeep-prod-1-http.entrypoints: web
      traefik.http.routers.karakeep-prod-1-http.rule: Host(`karakeep.jakerob.pro`)
      traefik.http.routers.karakeep-prod-1-http.middlewares: websecure-redirect-permanent@file
      traefik.http.routers.karakeep-prod-1-https.entrypoints: websecure
      traefik.http.routers.karakeep-prod-1-https.rule: Host(`karakeep.jakerob.pro`)
      traefik.http.routers.karakeep-prod-1-https.tls: true
      traefik.http.routers.karakeep-prod-1-https.tls.certresolver: cloudflare
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - internal
  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ./meilisearch:/meili_data
    networks:
      - internal
