# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3.json

# Tunnel sitting in between Cloud Traefik and Local Traefik

global:
  checkNewVersion: false
  sendAnonymousUsage: false

# -- (Optional) Change Log Level and Format here...
#     - loglevels [TRACE, DEBUG, INFO, WARN, ERROR, FATAL, PANIC]
#     - format [common, json, logfmt]
log:
  level: WARN
#  format: common
#  filePath: /var/log/traefik/traefik.log

# -- (Optional) Enable Accesslog and change Format here...
#     - format [common, json, logfmt]
# accesslog:
#   format: common
#   filePath: /var/log/traefik/access.log

# -- (Optional) Enable API and Dashboard here, don't do in production
api:
  dashboard: true
  insecure: true

# -- Change EntryPoints here...
entryPoints:
  web:
    address: :80
    
  websecure:
    address: :443

# We won't give this resolver our API key, so it won't be able to refresh
certificatesResolvers:
  cloudflare:
    acme:
      email: jroberts.g1ql8@simplelogin.com
      storage: /etc/traefik/certs/cloudflare-acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"

# -- (Optional) Disable TLS Cert verification check
serversTransport:
  insecureSkipVerify: true

# -- (Optional) Overwrite Default Certificates
# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: /etc/traefik/certs/cert.pem
#         keyFile: /etc/traefik/certs/cert-key.pem
# -- (Optional) Disable TLS version 1.0 and 1.1
#   options:
#     default:
#       minVersion: VersionTLS12

providers:
  file:
    directory: /etc/traefik/conf/
    watch: false
