# Generated by gen-imports.py. Each block adopts a record that already
# exists in Cloudflare so Terraform stops trying to create it.
# Safe to re-run: a block for an already-imported record is a no-op.
#
import {
  to = cloudflare_dns_record.records["pbj-node-1"]
  id = "6e98165e20ed0ba1b018f543c6ab4285/5e6f2600261365148e7c46358da5b7f5"
}

import {
  to = cloudflare_dns_record.records["pbj_catch_all"]
  id = "6e98165e20ed0ba1b018f543c6ab4285/6f1f9e5a31e79fdec6938a8ff1c0e591"
}

import {
  to = cloudflare_dns_record.records["pbj-pi-1-v6"]
  id = "6e98165e20ed0ba1b018f543c6ab4285/7e49eaa637c06b26767cba82761d9910"
}
