---
name: webnut

networks:
  frontend:
    external: true

services:
  nut:
    image: docker.io/edgd1er/webnut:latest
    container_name: webnut
    environment:
      - UPS_HOST=192.168.42.10
      - UPS_PORT=3493
      - UPS_USER=${UPS_USER}
      - UPS_PASSWORD=${UPS_PASSWORD}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - frontend
    labels:
      traefik.enable: true
      traefik.http.services.webnut-prod-1.loadBalancer.server.port: 6543
      traefik.http.routers.webnut-prod-1-http.entrypoints: web
      traefik.http.routers.webnut-prod-1-http.rule: Host(`webnut.lhr1.jakerob.pro`)
      traefik.http.routers.webnut-prod-1-http.middlewares: websecure-redirect-permanent@file
      traefik.http.routers.webnut-prod-1-https.entrypoints: websecure
      traefik.http.routers.webnut-prod-1-https.rule: Host(`webnut.lhr1.jakerob.pro`)
      traefik.http.routers.webnut-prod-1-https.tls: true
      traefik.http.routers.webnut-prod-1-https.tls.certresolver: cloudflare
